### ISSUE TITLE
Add GitHub Action for building the website

### ISSUE THREAD

**Issue by JDRomano2** [RomanoLab/comptox_ai#51]
We need to define a GitHub action that builds the ComptoxAI website, including using Sphinx to generate HTML for all of the documentation. In summary, the action should:

1. Install the python package along with any dependencies needed to build the documentation
2. Run `make html` in the `docs/` directory
3. Build the dynamic data browsing React app (found in `web/packages/app`)
4. Copy the compiled version of the app into the correct location in the website's file structure

**Comment by yunchae-kim** [comment]
There is a reason why I used a very simple version of Sphinx Build action (https://github.com/marketplace/actions/doc-build?version=v1.0) instead of other more complicated actions in the GitHub market.
1. Using other methods creates an error due to trouble finding the proper location for the codes necessary for building with Sphinx.
2. The other create package conflict issues, notably between Python, Sphinx, and Jinja2.
3. The simple version we are using does not require us to install all the pip packages, making the action process quicker.

What I hope to modify/add in the future would be
- Check detailed errors and log them as we push (https://github.com/marketplace/actions/sphinx-build-composite)
- Fix the dependency issue warnings in both Sphinx and React build.

**Comment by JDRomano2** [comment]
The above sounds great, I agree with all of it.
